-- ============================================
-- AUTO-GENERATED COMPREHENSIVE SCHEMA MIGRATION
-- SmartLenderUp - Add ALL Missing Columns
-- ============================================
-- This script adds all potentially missing columns
-- across all tables in the SmartLenderUp platform
-- Safe to run multiple times (uses IF NOT EXISTS)
-- ============================================

-- SHAREHOLDERS TABLE
ALTER TABLE shareholders 
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS share_capital NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ownership_percentage NUMERIC(5, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bank_account JSONB,
  ADD COLUMN IF NOT EXISTS total_dividends NUMERIC(15, 2) DEFAULT 0;

-- SHAREHOLDER_TRANSACTIONS TABLE
ALTER TABLE shareholder_transactions
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS payment_reference TEXT,
  ADD COLUMN IF NOT EXISTS receipt_number TEXT,
  ADD COLUMN IF NOT EXISTS processed_by TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS bank_account_id TEXT;

-- BANK_ACCOUNTS TABLE
ALTER TABLE bank_accounts
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS account_name TEXT,
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'KES',
  ADD COLUMN IF NOT EXISTS opening_balance NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS opening_date TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS created_date TEXT,
  ADD COLUMN IF NOT EXISTS last_updated TEXT;

-- EXPENSES TABLE
ALTER TABLE expenses
  ADD COLUMN IF NOT EXISTS subcategory TEXT,
  ADD COLUMN IF NOT EXISTS payee_name TEXT,
  ADD COLUMN IF NOT EXISTS payment_reference TEXT,
  ADD COLUMN IF NOT EXISTS expense_date TEXT,
  ADD COLUMN IF NOT EXISTS receipt_number TEXT,
  ADD COLUMN IF NOT EXISTS attachments JSONB,
  ADD COLUMN IF NOT EXISTS approved_by TEXT,
  ADD COLUMN IF NOT EXISTS approved_date TEXT,
  ADD COLUMN IF NOT EXISTS paid_by TEXT,
  ADD COLUMN IF NOT EXISTS paid_date TEXT,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS created_date TEXT,
  ADD COLUMN IF NOT EXISTS bank_account_id TEXT,
  ADD COLUMN IF NOT EXISTS payment_type TEXT;

-- PAYEES TABLE
ALTER TABLE payees
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS bank_account JSONB,
  ADD COLUMN IF NOT EXISTS mpesa_number TEXT,
  ADD COLUMN IF NOT EXISTS tax_pin TEXT,
  ADD COLUMN IF NOT EXISTS kra_pin TEXT,
  ADD COLUMN IF NOT EXISTS contact_person TEXT,
  ADD COLUMN IF NOT EXISTS total_paid NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_payment_date TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active',
  ADD COLUMN IF NOT EXISTS created_date TEXT;

-- GROUPS TABLE
ALTER TABLE groups
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS meeting_day TEXT,
  ADD COLUMN IF NOT EXISTS meeting_time TEXT,
  ADD COLUMN IF NOT EXISTS chairperson_phone TEXT,
  ADD COLUMN IF NOT EXISTS secretary_phone TEXT,
  ADD COLUMN IF NOT EXISTS treasurer_phone TEXT,
  ADD COLUMN IF NOT EXISTS total_members INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS active_members INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS group_status TEXT,
  ADD COLUMN IF NOT EXISTS total_loans NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS default_rate NUMERIC(5, 2) DEFAULT 0;

-- TASKS TABLE
ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS assigned_by TEXT,
  ADD COLUMN IF NOT EXISTS created_date TEXT,
  ADD COLUMN IF NOT EXISTS completed_date TEXT,
  ADD COLUMN IF NOT EXISTS related_entity_type TEXT,
  ADD COLUMN IF NOT EXISTS related_entity_id TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;

-- PAYROLL_RUNS TABLE
ALTER TABLE payroll_runs
  ADD COLUMN IF NOT EXISTS period TEXT,
  ADD COLUMN IF NOT EXISTS pay_date TEXT,
  ADD COLUMN IF NOT EXISTS employees JSONB,
  ADD COLUMN IF NOT EXISTS total_gross_pay NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_net_pay NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS created_date TEXT,
  ADD COLUMN IF NOT EXISTS approved_by TEXT,
  ADD COLUMN IF NOT EXISTS approved_date TEXT,
  ADD COLUMN IF NOT EXISTS paid_date TEXT,
  ADD COLUMN IF NOT EXISTS bank_account_id TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;

-- FUNDING_TRANSACTIONS TABLE
ALTER TABLE funding_transactions
  ADD COLUMN IF NOT EXISTS bank_account_id TEXT,
  ADD COLUMN IF NOT EXISTS date TEXT,
  ADD COLUMN IF NOT EXISTS reference TEXT,
  ADD COLUMN IF NOT EXISTS shareholder_id TEXT,
  ADD COLUMN IF NOT EXISTS shareholder_name TEXT,
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS depositor_name TEXT,
  ADD COLUMN IF NOT EXISTS transaction_type TEXT,
  ADD COLUMN IF NOT EXISTS related_loan_id TEXT;

-- DISBURSEMENTS TABLE
ALTER TABLE disbursements
  ADD COLUMN IF NOT EXISTS client_id TEXT,
  ADD COLUMN IF NOT EXISTS client_name TEXT,
  ADD COLUMN IF NOT EXISTS scheduled_date TEXT,
  ADD COLUMN IF NOT EXISTS actual_date TEXT,
  ADD COLUMN IF NOT EXISTS channel TEXT,
  ADD COLUMN IF NOT EXISTS mpesa_number TEXT,
  ADD COLUMN IF NOT EXISTS bank_name TEXT,
  ADD COLUMN IF NOT EXISTS account_number TEXT,
  ADD COLUMN IF NOT EXISTS reference TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Scheduled',
  ADD COLUMN IF NOT EXISTS processed_by TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS created_date TEXT,
  ADD COLUMN IF NOT EXISTS created_by TEXT;

-- APPROVALS TABLE
ALTER TABLE approvals
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS requested_by TEXT,
  ADD COLUMN IF NOT EXISTS request_date TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC(15, 2),
  ADD COLUMN IF NOT EXISTS client_id TEXT,
  ADD COLUMN IF NOT EXISTS client_name TEXT,
  ADD COLUMN IF NOT EXISTS priority TEXT,
  ADD COLUMN IF NOT EXISTS approver TEXT,
  ADD COLUMN IF NOT EXISTS approval_date TEXT,
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS related_id TEXT,
  ADD COLUMN IF NOT EXISTS phase INTEGER,
  ADD COLUMN IF NOT EXISTS disbursement_data JSONB;

-- JOURNAL_ENTRIES TABLE
ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS entry_number TEXT,
  ADD COLUMN IF NOT EXISTS date TEXT,
  ADD COLUMN IF NOT EXISTS reference TEXT,
  ADD COLUMN IF NOT EXISTS source_type TEXT,
  ADD COLUMN IF NOT EXISTS source_id TEXT,
  ADD COLUMN IF NOT EXISTS lines JSONB,
  ADD COLUMN IF NOT EXISTS total_debit NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_credit NUMERIC(15, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS created_date TEXT,
  ADD COLUMN IF NOT EXISTS posted_date TEXT,
  ADD COLUMN IF NOT EXISTS reversed_date TEXT,
  ADD COLUMN IF NOT EXISTS reversed_by TEXT,
  ADD COLUMN IF NOT EXISTS reversal_reason TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;

-- PROCESSING_FEE_RECORDS TABLE
ALTER TABLE processing_fee_records
  ADD COLUMN IF NOT EXISTS client_id TEXT,
  ADD COLUMN IF NOT EXISTS client_name TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC(15, 2),
  ADD COLUMN IF NOT EXISTS percentage NUMERIC(5, 2),
  ADD COLUMN IF NOT EXISTS loan_amount NUMERIC(15, 2),
  ADD COLUMN IF NOT EXISTS recorded_date TEXT,
  ADD COLUMN IF NOT EXISTS recorded_by TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS waived_by TEXT,
  ADD COLUMN IF NOT EXISTS waived_reason TEXT,
  ADD COLUMN IF NOT EXISTS payment_method TEXT;

-- TICKETS TABLE
ALTER TABLE tickets
  ADD COLUMN IF NOT EXISTS ticket_number TEXT,
  ADD COLUMN IF NOT EXISTS client_id TEXT,
  ADD COLUMN IF NOT EXISTS client_name TEXT,
  ADD COLUMN IF NOT EXISTS subject TEXT,
  ADD COLUMN IF NOT EXISTS channel TEXT,
  ADD COLUMN IF NOT EXISTS created_date TEXT,
  ADD COLUMN IF NOT EXISTS updated_date TEXT,
  ADD COLUMN IF NOT EXISTS resolved_date TEXT,
  ADD COLUMN IF NOT EXISTS resolution TEXT;

-- KYC_RECORDS TABLE
ALTER TABLE kyc_records
  ADD COLUMN IF NOT EXISTS client_name TEXT,
  ADD COLUMN IF NOT EXISTS risk_rating TEXT,
  ADD COLUMN IF NOT EXISTS last_review_date TEXT,
  ADD COLUMN IF NOT EXISTS next_review_date TEXT,
  ADD COLUMN IF NOT EXISTS national_id_verified BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS address_verified BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS biometrics_collected BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS documents_on_file JSONB,
  ADD COLUMN IF NOT EXISTS reviewed_by TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;

-- AUDIT_LOGS TABLE
ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS timestamp TEXT,
  ADD COLUMN IF NOT EXISTS user_id TEXT,
  ADD COLUMN IF NOT EXISTS user_name TEXT,
  ADD COLUMN IF NOT EXISTS module TEXT,
  ADD COLUMN IF NOT EXISTS changes TEXT,
  ADD COLUMN IF NOT EXISTS ip_address TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT;

-- ============================================
-- MIGRATION COMPLETE
-- ============================================

DO $$
BEGIN
  RAISE NOTICE '✅ Schema migration complete!';
  RAISE NOTICE '✅ All missing columns have been added safely.';
  RAISE NOTICE '✅ Existing data has been preserved.';
  RAISE NOTICE '✅ You can now use all features without "column not found" errors!';
END $$;
