/**
 * Utility to populate sample/demo data for testing
 * This will create sample clients, loans, loan products, and other data
 */

export function populateSampleData(): boolean {
  console.log('🔄 Populating sample data...');
  
  // Sample Loan Products
  const sampleLoanProducts = [
    {
      id: 'PROD-001',
      name: 'Business Loan',
      code: 'BL-001',
      description: 'Short-term loans for small businesses',
      minAmount: 10000,
      maxAmount: 500000,
      defaultAmount: 100000,
      interestRate: 12,
      interestType: 'Reducing Balance',
      minTerm: 3,
      maxTerm: 24,
      defaultTerm: 12,
      termUnit: 'Months',
      repaymentFrequency: 'Monthly',
      processingFee: 2,
      processingFeeType: 'Percentage',
      insuranceFee: 1,
      disbursementMethod: 'Bank Transfer',
      requiresCollateral: true,
      requiresGuarantor: true,
      gracePeriod: 0,
      penaltyRate: 2,
      status: 'Active',
      createdDate: new Date().toISOString(),
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'PROD-002',
      name: 'Personal Loan',
      code: 'PL-001',
      description: 'Unsecured personal loans',
      minAmount: 5000,
      maxAmount: 200000,
      defaultAmount: 50000,
      interestRate: 15,
      interestType: 'Reducing Balance',
      minTerm: 1,
      maxTerm: 12,
      defaultTerm: 6,
      termUnit: 'Months',
      repaymentFrequency: 'Monthly',
      processingFee: 3,
      processingFeeType: 'Percentage',
      insuranceFee: 1,
      disbursementMethod: 'M-Pesa',
      requiresCollateral: false,
      requiresGuarantor: true,
      gracePeriod: 0,
      penaltyRate: 2,
      status: 'Active',
      createdDate: new Date().toISOString(),
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'PROD-003',
      name: 'Emergency Loan',
      code: 'EL-001',
      description: 'Quick access loans for emergencies',
      minAmount: 2000,
      maxAmount: 50000,
      defaultAmount: 20000,
      interestRate: 18,
      interestType: 'Flat',
      minTerm: 1,
      maxTerm: 6,
      defaultTerm: 3,
      termUnit: 'Months',
      repaymentFrequency: 'Monthly',
      processingFee: 5,
      processingFeeType: 'Percentage',
      insuranceFee: 1,
      disbursementMethod: 'M-Pesa',
      requiresCollateral: false,
      requiresGuarantor: false,
      gracePeriod: 0,
      penaltyRate: 3,
      status: 'Active',
      createdDate: new Date().toISOString(),
      lastUpdated: new Date().toISOString()
    }
  ];
  
  // Sample Clients
  const sampleClients = [
    {
      id: 'CL001',
      name: 'Sarah Mwangi',
      email: 'sarah.mwangi@example.com',
      phone: '+254712345678',
      idNumber: '12345678',
      address: '123 Kenyatta Avenue',
      city: 'Nairobi',
      county: 'Nairobi',
      occupation: 'Business Owner',
      employer: 'Self Employed',
      monthlyIncome: 80000,
      dateOfBirth: '1985-05-15',
      gender: 'Female' as const,
      maritalStatus: 'Married',
      nextOfKin: {
        name: 'John Mwangi',
        relationship: 'Spouse',
        phone: '+254722334455'
      },
      status: 'Active' as const,
      creditScore: 750,
      riskRating: 'Low' as const,
      clientType: 'individual' as const,
      branch: 'Nairobi Branch',
      joinDate: '2024-01-15',
      createdBy: 'Victor Muthama',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'CL002',
      name: 'James Omondi',
      email: 'james.omondi@example.com',
      phone: '+254723456789',
      idNumber: '23456789',
      address: '45 Oginga Odinga Road',
      city: 'Kisumu',
      county: 'Kisumu',
      occupation: 'Teacher',
      employer: 'Kisumu Primary School',
      monthlyIncome: 55000,
      dateOfBirth: '1980-08-22',
      gender: 'Male' as const,
      maritalStatus: 'Single',
      nextOfKin: {
        name: 'Jane Omondi',
        relationship: 'Sister',
        phone: '+254733445566'
      },
      status: 'Active' as const,
      creditScore: 680,
      riskRating: 'Medium' as const,
      clientType: 'individual' as const,
      branch: 'Kisumu Branch',
      joinDate: '2024-02-10',
      createdBy: 'Ben Mbuvi',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'CL003',
      name: 'Grace Njeri',
      email: 'grace.njeri@example.com',
      phone: '+254734567890',
      idNumber: '34567890',
      address: '78 Kenyatta Street',
      city: 'Nakuru',
      county: 'Nakuru',
      occupation: 'Shopkeeper',
      employer: 'Self Employed',
      monthlyIncome: 65000,
      dateOfBirth: '1988-11-10',
      gender: 'Female' as const,
      maritalStatus: 'Married',
      nextOfKin: {
        name: 'Peter Njeri',
        relationship: 'Spouse',
        phone: '+254744556677'
      },
      status: 'Active' as const,
      creditScore: 720,
      riskRating: 'Low' as const,
      clientType: 'individual' as const,
      branch: 'Nakuru Branch',
      joinDate: '2024-03-05',
      createdBy: 'Victor Muthama',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'CL004',
      name: 'Peter Kamau',
      email: 'peter.kamau@example.com',
      phone: '+254745678901',
      idNumber: '45678901',
      address: '90 Moi Avenue',
      city: 'Mombasa',
      county: 'Mombasa',
      occupation: 'Driver',
      employer: 'Mombasa Transport',
      monthlyIncome: 45000,
      dateOfBirth: '1990-03-18',
      gender: 'Male' as const,
      maritalStatus: 'Single',
      nextOfKin: {
        name: 'Mary Kamau',
        relationship: 'Mother',
        phone: '+254755667788'
      },
      status: 'Active' as const,
      creditScore: 690,
      riskRating: 'Medium' as const,
      clientType: 'individual' as const,
      branch: 'Mombasa Branch',
      joinDate: '2024-03-20',
      createdBy: 'Ben Mbuvi',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'CL005',
      name: 'Mary Achieng',
      email: 'mary.achieng@example.com',
      phone: '+254756789012',
      idNumber: '56789012',
      address: '12 Uganda Road',
      city: 'Eldoret',
      county: 'Uasin Gishu',
      occupation: 'Farmer',
      employer: 'Self Employed',
      monthlyIncome: 70000,
      dateOfBirth: '1982-07-25',
      gender: 'Female' as const,
      maritalStatus: 'Widow',
      nextOfKin: {
        name: 'David Achieng',
        relationship: 'Son',
        phone: '+254766778899'
      },
      status: 'Active' as const,
      creditScore: 800,
      riskRating: 'Low' as const,
      clientType: 'individual' as const,
      branch: 'Eldoret Branch',
      joinDate: '2024-04-01',
      createdBy: 'Victor Muthama',
      lastUpdated: new Date().toISOString()
    }
  ];
  
  // Sample Loans
  const sampleLoans = [
    {
      id: 'LOAN-001',
      clientId: 'CL001',
      clientName: 'Sarah Mwangi',
      productId: 'PROD-001',
      productName: 'Business Loan',
      principalAmount: 100000,
      interestRate: 12,
      interestType: 'Reducing Balance' as const,
      term: 12,
      termUnit: 'Months' as const,
      repaymentFrequency: 'Monthly' as const,
      disbursementDate: '2024-06-01',
      firstRepaymentDate: '2024-07-01',
      maturityDate: '2025-06-01',
      status: 'Active' as const,
      approvedBy: 'Victor Muthama',
      approvedDate: '2024-05-28',
      disbursedBy: 'Victor Muthama',
      disbursedDate: '2024-06-01',
      totalInterest: 12000,
      totalRepayable: 112000,
      installmentAmount: 9333,
      numberOfInstallments: 12,
      paidAmount: 45000,
      outstandingBalance: 67000,
      principalOutstanding: 60000,
      interestOutstanding: 7000,
      daysInArrears: 0,
      arrearsAmount: 0,
      overdueAmount: 0,
      penaltyAmount: 0,
      purpose: 'Business expansion',
      applicationDate: '2024-05-20',
      createdBy: 'Victor Muthama',
      lastPaymentDate: '2024-11-05',
      lastPaymentAmount: 9333,
      nextPaymentDate: '2024-12-05',
      nextPaymentAmount: 9333,
      loanOfficer: 'Victor Muthama',
      createdDate: '2024-05-20',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'LOAN-002',
      clientId: 'CL002',
      clientName: 'James Omondi',
      productId: 'PROD-002',
      productName: 'Personal Loan',
      principalAmount: 50000,
      interestRate: 15,
      interestType: 'Reducing Balance' as const,
      term: 6,
      termUnit: 'Months' as const,
      repaymentFrequency: 'Monthly' as const,
      disbursementDate: '2024-07-15',
      firstRepaymentDate: '2024-08-15',
      maturityDate: '2025-01-15',
      status: 'Active' as const,
      approvedBy: 'Ben Mbuvi',
      approvedDate: '2024-07-10',
      disbursedBy: 'Ben Mbuvi',
      disbursedDate: '2024-07-15',
      totalInterest: 7500,
      totalRepayable: 57500,
      installmentAmount: 9583,
      numberOfInstallments: 6,
      paidAmount: 20000,
      outstandingBalance: 37500,
      principalOutstanding: 33000,
      interestOutstanding: 4500,
      daysInArrears: 0,
      arrearsAmount: 0,
      overdueAmount: 0,
      penaltyAmount: 0,
      purpose: 'Personal development',
      applicationDate: '2024-07-05',
      createdBy: 'Ben Mbuvi',
      lastPaymentDate: '2024-10-15',
      lastPaymentAmount: 9583,
      nextPaymentDate: '2024-12-15',
      nextPaymentAmount: 9583,
      loanOfficer: 'Ben Mbuvi',
      createdDate: '2024-07-05',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'LOAN-003',
      clientId: 'CL003',
      clientName: 'Grace Njeri',
      productId: 'PROD-001',
      productName: 'Business Loan',
      principalAmount: 150000,
      interestRate: 12,
      interestType: 'Reducing Balance' as const,
      term: 18,
      termUnit: 'Months' as const,
      repaymentFrequency: 'Monthly' as const,
      disbursementDate: '2024-08-01',
      firstRepaymentDate: '2024-09-01',
      maturityDate: '2026-02-01',
      status: 'Active' as const,
      approvedBy: 'Victor Muthama',
      approvedDate: '2024-07-28',
      disbursedBy: 'Victor Muthama',
      disbursedDate: '2024-08-01',
      totalInterest: 27000,
      totalRepayable: 177000,
      installmentAmount: 9833,
      numberOfInstallments: 18,
      paidAmount: 30000,
      outstandingBalance: 147000,
      principalOutstanding: 130000,
      interestOutstanding: 17000,
      daysInArrears: 0,
      arrearsAmount: 0,
      overdueAmount: 0,
      penaltyAmount: 0,
      purpose: 'Shop renovation',
      applicationDate: '2024-07-20',
      createdBy: 'Victor Muthama',
      lastPaymentDate: '2024-11-01',
      lastPaymentAmount: 9833,
      nextPaymentDate: '2024-12-01',
      nextPaymentAmount: 9833,
      loanOfficer: 'Victor Muthama',
      createdDate: '2024-07-20',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'LOAN-004',
      clientId: 'CL004',
      clientName: 'Peter Kamau',
      productId: 'PROD-003',
      productName: 'Emergency Loan',
      principalAmount: 25000,
      interestRate: 18,
      interestType: 'Flat' as const,
      term: 3,
      termUnit: 'Months' as const,
      repaymentFrequency: 'Monthly' as const,
      disbursementDate: '2024-10-01',
      firstRepaymentDate: '2024-11-01',
      maturityDate: '2024-12-31',
      status: 'Active' as const,
      approvedBy: 'Ben Mbuvi',
      approvedDate: '2024-09-28',
      disbursedBy: 'Ben Mbuvi',
      disbursedDate: '2024-10-01',
      totalInterest: 4500,
      totalRepayable: 29500,
      installmentAmount: 9833,
      numberOfInstallments: 3,
      paidAmount: 10000,
      outstandingBalance: 19500,
      principalOutstanding: 16000,
      interestOutstanding: 3500,
      daysInArrears: 0,
      arrearsAmount: 0,
      overdueAmount: 0,
      penaltyAmount: 0,
      purpose: 'Medical emergency',
      applicationDate: '2024-09-25',
      createdBy: 'Ben Mbuvi',
      lastPaymentDate: '2024-11-01',
      lastPaymentAmount: 9833,
      nextPaymentDate: '2024-12-01',
      nextPaymentAmount: 9833,
      loanOfficer: 'Ben Mbuvi',
      createdDate: '2024-09-25',
      lastUpdated: new Date().toISOString()
    },
    {
      id: 'LOAN-005',
      clientId: 'CL005',
      clientName: 'Mary Achieng',
      productId: 'PROD-002',
      productName: 'Personal Loan',
      principalAmount: 80000,
      interestRate: 15,
      interestType: 'Reducing Balance' as const,
      term: 12,
      termUnit: 'Months' as const,
      repaymentFrequency: 'Monthly' as const,
      disbursementDate: '2024-09-01',
      firstRepaymentDate: '2024-10-01',
      maturityDate: '2025-09-01',
      status: 'Active' as const,
      approvedBy: 'Victor Muthama',
      approvedDate: '2024-08-28',
      disbursedBy: 'Victor Muthama',
      disbursedDate: '2024-09-01',
      totalInterest: 12000,
      totalRepayable: 92000,
      installmentAmount: 7667,
      numberOfInstallments: 12,
      paidAmount: 35000,
      outstandingBalance: 57000,
      principalOutstanding: 50000,
      interestOutstanding: 7000,
      daysInArrears: 0,
      arrearsAmount: 0,
      overdueAmount: 0,
      penaltyAmount: 0,
      purpose: 'Farm equipment',
      applicationDate: '2024-08-20',
      createdBy: 'Victor Muthama',
      lastPaymentDate: '2024-11-01',
      lastPaymentAmount: 7667,
      nextPaymentDate: '2024-12-01',
      nextPaymentAmount: 7667,
      loanOfficer: 'Victor Muthama',
      createdDate: '2024-08-20',
      lastUpdated: new Date().toISOString()
    }
  ];
  
  // Sample Repayments
  const sampleRepayments = [
    {
      id: 'REP-001',
      loanId: 'LOAN-001',
      clientId: 'CL001',
      clientName: 'Sarah Mwangi',
      amount: 9333,
      principal: 8333,
      interest: 1000,
      penalty: 0,
      paymentMethod: 'M-Pesa' as const,
      paymentReference: 'SH92KD7F3Q',
      paymentDate: '2024-07-05',
      receiptNumber: 'RCP-001',
      receivedBy: 'Victor Muthama',
      status: 'Approved' as const,
      approvedBy: 'Victor Muthama',
      approvedDate: '2024-07-05',
      createdDate: '2024-07-05'
    },
    {
      id: 'REP-002',
      loanId: 'LOAN-001',
      clientId: 'CL001',
      clientName: 'Sarah Mwangi',
      amount: 9333,
      principal: 8400,
      interest: 933,
      penalty: 0,
      paymentMethod: 'M-Pesa' as const,
      paymentReference: 'SH83LD6E2P',
      paymentDate: '2024-08-05',
      receiptNumber: 'RCP-002',
      receivedBy: 'Victor Muthama',
      status: 'Approved' as const,
      approvedBy: 'Victor Muthama',
      approvedDate: '2024-08-05',
      createdDate: '2024-08-05'
    },
    {
      id: 'REP-003',
      loanId: 'LOAN-001',
      clientId: 'CL001',
      clientName: 'Sarah Mwangi',
      amount: 9333,
      principal: 8467,
      interest: 866,
      penalty: 0,
      paymentMethod: 'Bank Transfer' as const,
      paymentReference: 'BNK123456',
      paymentDate: '2024-09-05',
      receiptNumber: 'RCP-003',
      receivedBy: 'Victor Muthama',
      status: 'Approved' as const,
      approvedBy: 'Victor Muthama',
      approvedDate: '2024-09-05',
      createdDate: '2024-09-05'
    },
    {
      id: 'REP-004',
      loanId: 'LOAN-002',
      clientId: 'CL002',
      clientName: 'James Omondi',
      amount: 9583,
      principal: 8583,
      interest: 1000,
      penalty: 0,
      paymentMethod: 'M-Pesa' as const,
      paymentReference: 'SH74ME5D1K',
      paymentDate: '2024-08-20',
      receiptNumber: 'RCP-004',
      receivedBy: 'Ben Mbuvi',
      status: 'Approved' as const,
      approvedBy: 'Ben Mbuvi',
      approvedDate: '2024-08-20',
      createdDate: '2024-08-20'
    },
    {
      id: 'REP-005',
      loanId: 'LOAN-002',
      clientId: 'CL002',
      clientName: 'James Omondi',
      amount: 10417,
      principal: 9417,
      interest: 1000,
      penalty: 0,
      paymentMethod: 'Cash' as const,
      paymentReference: 'CASH-001',
      paymentDate: '2024-09-20',
      receiptNumber: 'RCP-005',
      receivedBy: 'Ben Mbuvi',
      status: 'Approved' as const,
      approvedBy: 'Ben Mbuvi',
      approvedDate: '2024-09-20',
      createdDate: '2024-09-20'
    }
  ];
  
  // Save to localStorage
  localStorage.setItem('bvfunguo_loan_products', JSON.stringify(sampleLoanProducts));
  localStorage.setItem('bvfunguo_clients', JSON.stringify(sampleClients));
  localStorage.setItem('bvfunguo_loans', JSON.stringify(sampleLoans));
  localStorage.setItem('bvfunguo_repayments', JSON.stringify(sampleRepayments));
  localStorage.setItem('bvfunguo_savings_accounts', JSON.stringify([]));
  localStorage.setItem('bvfunguo_savings_transactions', JSON.stringify([]));
  
  // Mark as initialized with correct version
  localStorage.setItem('bvfunguo_initialized', 'true');
  localStorage.setItem('bvfunguo_data_version', '2.5');
  
  console.log('✅ Sample data populated successfully!');
  console.log('📊 Created:');
  console.log('  - 3 loan products');
  console.log('  - 5 clients');
  console.log('  - 5 active loans');
  console.log('  - 5 repayment records');
  console.log('🔄 Please refresh the page to see the data...');
  
  return true;
}

// Add to window for easy access from browser console
if (typeof window !== 'undefined') {
  (window as any).populateSampleData = populateSampleData;
  console.log('💡 Sample data utility loaded. Type populateSampleData() in console to populate demo data.');
}