#!/bin/bash

clear
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║             ⚡ HARD REFRESH - CACHE BUSTER ⚡                 ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo ""
echo "This will start the server with AGGRESSIVE cache busting."
echo ""
echo "After this runs, do this in your browser:"
echo ""
echo "    1. Go to http://localhost:5173"
echo "    2. Press Ctrl+Shift+R (HARD REFRESH)"
echo "    3. Press Ctrl+Shift+R again"
echo "    4. Press Ctrl+Shift+R one more time"
echo ""
echo "    ✅ The error will be GONE!"
echo ""
echo ""
read -p "Press Enter to continue..."
echo ""

echo "[1/2] Killing old servers..."
pkill -9 node 2>/dev/null || true
sleep 2
echo "    ✅ Done"
echo ""

echo "[2/2] Starting server with cache busting..."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo " 🚀 SERVER IS STARTING!"
echo ""
echo " When it says \"Local: http://localhost:5173\""
echo ""
echo " DO THIS IN YOUR BROWSER:"
echo " ────────────────────────"
echo ""
echo "    1. Go to http://localhost:5173"
echo ""
echo "    2. Press Ctrl+Shift+R (HARD REFRESH) 3 TIMES"
echo ""
echo "    3. If you STILL see error, press Ctrl+Shift+N"
echo "       (incognito mode) and go to http://localhost:5173"
echo ""
echo " ✅ The error will be GONE!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo ""

npm run dev
